theme: minima
markdown: kramdown

title: |-
    Self-Contained Calibration of an Elastic Humanoid Upper Body 
    Using Only a Head-Mounted RGB Camera

author: johannes.tenhumberg@tum.de

header_pages:
  - _pages/robot.md
  - _pages/camera.md
  - _pages/methods.md
  - _pages/results.md
  - _pages/dataset.md
  - _pages/related-work.md
  - _pages/aidx-lab.md

include:
    - _pages

plugins:
  - jekyll-redirect-from

exclude: 
    - .gitignore
    - Gemfile
    - README.md
